const powerManage = {
     //顾客
     "customer":[{
        name:'Product'
     },{
       name:'productList'
     },{
       name:'productAdd'
     }],
     //管理者
     "admin":[{
      //顾客
      "customer":[{
         name:'Product'
      },{
        name:'productList'
      },{
        name:'productAdd'
      },{
        name:''
     }]
  }
